- docs/community/governance-review-week.md
- `/community/governance-review-week`
Described Governance Review Week
Wrote about its structure and timeline
Wrote about its purpose
Added links and questions
Governance Review Week generated a lot of value in the last two years. The questions were discussed were thought carefully and answered sincerely.
1. New members will already know about the event and its history.
2. It will be easier to organize in the future by looking at the archives.
3. Other societies can learn from our system. (TLS already does).
Co-Authored-By: Ayush Kaushal <ayushk4@gmail.com>
> Create doc for Governance Review Week

- community/one-on-one.md
- `/community/one-on-one`
Add a doc about 1:1 meetups. Added guidelines for the mentors and mentees. Added general notes as well.
This is a very noble idea. It should be preserved. Every year, new sets of mentor-mentee can look up the guidelines, to begin with.
> Create a doc about 1:1s

- events/freshers-selection.md
- `/events/freshers-selection`
Added a doc about recruiting new people. This doc needs to be updated every year. Added notes about the procedure and guidelines. Added positive and negative points of new members as well as red flags. Added FAQ and Archive section.
We should document because hiring can be very subjective. We need uniformity among all the interviewers across the years. However, the doc is just a guideline and must be updated every year.
The doc mentions our philosophy on a broad level. This information is not sensitive to the public.
> Add the doc about Freshers Selection

- community/governance.md
These guidelines are very essential for every advisor to follow.
Closing #10
> Add guidelines for advisors

- community/accounts.md
More rules and guidelines are yet to be added. Need some more time to think. Also, it would be highly appreciated to have feedback and discussion regarding this.
> document accounts related information

- community/governance.md
Change in path in :-
- `/community/governance`
> Removal of role of executive-members and some points on offboarding executives.

- community/code-of-conduct.md
- `/community/code-of-conduct`
> initial code of conduct / guideline to open discussion on how to avoid and handle cases of sexual harassment and bullying

- events/kwoc.md
Every year, the information about logistics is mostly carried verbally from one batch to another batch, and sometimes important things are missed out.  Happened the previous years with few things(like late registration in 2020, mail verification in 2019). 
I have tried including mostly the logistical aspects only. Let's include the technical aspects in corresponding repositories, as they keep changing from year to year. 
If there any important things missing, feel free to add them. And if there are any points that are too obvious and not necessary to mention OR vaguely written OR not of practical importance, do point them out.
- `/events/kwoc.md`
> Logistic guidelines for KWoC added in events' doc

- community/onboarding-offboarding.md
- `/community/onboarding`
We have a global google group, which was not specified in the instructions.
> Specific google group in onboarding

- community/event-checklist.md
Example:
- `/community/event-checklist`
This will make sure that we keep our youtube channel remains active, help students who missed the session and also students outside the KGP community.
> added instructions for recoreded sessions

- events/room-booking.md
Signed-off-by: rajivharlalka <rajivharlalka009@gmail.com>
- `/events/room-booking`
Added Room Booking guidelines
Ease for people in the future to know the process of room-booking
Will sharing this with just the current members serve our purpose? For example, how you plan to conduct an event next week is a private affair. But, how you generally do the event, should be documented.
> Add Room Booking Guidelines

- events/kwoc.md
`/events/kwoc.md`
updating based on kwoc 23 mistakes 
Will sharing this with just the current members serve our purpose? For example, how you plan to conduct an event next week is a private affair. But, how you generally do the event, should be documented.
**S**!
> Updated doc based on KWoC 23 mistakes

- events/kwoc.md
- `/events/kwoc.md`
Added a few more things we do in KWoC.
Some steps were missing on the documentation about how KWoC is organized. Gives us - the organizers - a checklist to check upon along with others getting further details on what all happens in KWoC
> more on kwoc

- events/freshers-selection.md
Example:
- `/events/freshers-selection`
- Archival of past 2 years FB post.
- Mentioning of `[mailing-scripts](https://github.com/kossiitkgp/mailing-scripts)` for ease in mailing
> Update docs on fresher's selection

- events/kwoc.md
- `/events/kwoc.md`
- removed a duplicated instance of FB account.
> removed duplicates

- events/lightning-talks.md
**path(s) which will be affected by this Pull Request.**
- `/events`
**Updates for Lightning Talks**
**Should be documented as it's a mandatory annual event**
> Added Lightning Talks Documentation

- community/onboarding-offboarding.md
- community/socials.md
- `/community/onboarding-offboarding.md`
- `/community/socials.md`
- Documenting social media handling guidelines will streamline the process of releasing posts.
- The onboarding/offboarding guidelines were updated to include transferring access of all social media accounts to the new executives.
- Release of posts will be faster.
Will sharing this with just the current members serve our …
> Added Social Media Handling Guidelines

- events/room-booking.md
**Path(s) which will be affected by this Pull Request.**
- `/events`
> Fix: Updated AV Cell form submission guideline

- events/kossprint.md
**Path(s) which will be affected by this Pull Request.**
- `/events`
> Added KOSSprint Documentation

- community/posters.md
Example:
- `/community/posters.md`
- Added guidelines for poster sizes, design, printing, and pasting.
- This would increase consistency in design and prevent any challenges faced during poster printing or placing during an event.
Will sharing this with just the current members serve our purpose? For example, how you plan to conduct an event next week is a private affair. But, how you generally do the event, should be documented.
> Added Poster Documentation

- community/posters.md
Example:
- `/events/posters.md`
As discussed with @chirag-ghosh it's fine to have more posters. He also mentioned to increase the count drastically, can discuss about this.
> Some changes based on practicallity

- events/git-and-github.md
> Git update

- community/onboarding-offboarding.md
Example:
- `/community/governance`
- `/events/index`
- `/new-section/new-article`
Will sharing this with just the current members serve our purpose? For example, how you plan to conduct an event next week is a private affair. But, how you generally do the event, should be documented.
> feat: slack channels and their naming

- events/room-booking.md
**Description**
Documenting updated room booking procedure to facilitate future bookings
**Path(s) affected by this Pull Request:**
- `/events/room-booking`
> Updated room booking procedure
